name: Publish Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["7.4", "7.3", "7.2", "7.1", "7.0", "5.6", "5.5"]
    steps:
      - uses: actions/checkout@master
      - name: Build PHP ${{ matrix.version }} and publish to GitHub Registry
        uses: elgohr/Publish-Docker-Github-Action@2.22
        with:
          name: mileschou/composer:${{ matrix.version }}
          username: ${{ secrets.GITHUB_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}
          registry: ghcr.io
          dockerfile: ${{ matrix.version }}/Dockerfile
