name: Testing

on: [push]

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Composer action
        uses: mileschou/composer-action@master
        with:
          args: --help
  php71:
    runs-on: ubuntu-latest
    steps:
      - name: Composer action
        uses: mileschou/composer-action/7.1@master
        with:
          args: --help
